# Machine learning algorithms for coral bleaching classification 

## Load dataset

In [1]:
'''
    Import libraries
'''
from sklearn import datasets
import pandas as pd
import numpy as np
from numpy import mean
from numpy import std
import sklearn
import seaborn as sb
import matplotlib.pyplot as plt
from numpy import mean 
from numpy import std
import pingouin as pg   
from scipy.stats import shapiro
from scipy.stats import levene 
from scipy.stats import bartlett
from scipy.stats import kruskal
import scikit_posthocs as sp 
from scipy import stats
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import log_loss
from sklearn.metrics import roc_auc_score
from itertools import combinations, permutations
# check scikit-learn version
print(sklearn.__version__)

0.22.2.post1


C:\Users\bmped\Miniconda3\lib\site-packages\outdated\utils.py:18: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.3.10, the latest is 0.3.12.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  **kwargs


In [8]:
'''
    Load full dataset
'''
data = pd.read_csv('df_sst_clouds_rsds_mon_t.csv',sep = ";", low_memory=False)
len(data) 

33768

In [6]:
list(data.columns)

['Unnamed: 0',
 'ITEM_ID',
 'COUNTRY',
 'lat',
 'lon',
 'DHW_class',
 'SEVERITY_CODE',
 'MONTH',
 'YEAR',
 'CF_a_monmean',
 'DHM',
 'CLTa',
 'severity_bin',
 'sev_bin23',
 'CLT2017',
 'RSDS']

In [17]:
'''
    Subset DF by SEVERITY_CODE [0,1,2,3]
      Severity_code == "-1" is dropped
'''
#data = data.dropna() # drop rows that contains NaN's 
data = data[(data.SEVERITY_CODE == 0)|(data.SEVERITY_CODE == 1)|(data.SEVERITY_CODE == 2)|(data.SEVERITY_CODE == 3)] 
#data = data[(data.YEAR >= 2002)] # First year with more than 100 records
#data = data[(data.YEAR >= 2015) & (data.YEAR <= 2016)] # subset a single event
#data = data[(data.YEAR >= 1997) & (data.YEAR <= 1998)]
#list(data.columns)
data = data.dropna() # drop rows that contains NaN's (if any)
len(data)

33602

In [ ]:
'''
        Create dataframes to build independent models 
        Example:
        X1 = data[['var #1','var #2']]  ## features (dependen variable(s))
        X2 = data[['var #1','var #3']] 
        y = data[['independent variable']]  ## labels (indipendent variable)
        The object "X_" can be used to run a specific model, however, to keep it simple, the object "X" is going to be used and edited each time to get printed the results and avoid changing the code in subsequent steps" 
'''
# ## Features (dependent variable)
# X0=data[['DHW']] # better than any othe DHW metric
# X00=data[['DHW_9']] # better than DHW
# X1=data[['DHW', 'CF']] 
# X2=data[['DHW', 'CFrunmean7']]
# X3=data[['DHW', 'CFrunmean30']] 
# X4=data[['DHW', 'CFrunmean90']] # 
# X5=data[['DHW', 'CF_a']]
# X6=data[['DHW', 'CF_a_runmean7']] #
# X7=data[['DHW', 'CF_a_runmean30']] #
# X8=data[['DHW', 'CF_a_runmean90']] # +
# X9=data[['DHW_9','CF_a']] # + better than DHW_9
# X10=data[['DHW_9','CFrunmean7']]
# X11=data[['DHW_9','CFrunmean30']]
# X12=data[['DHW_9','CFrunmean90']]
# X13=data[['DHW_9','CF_a_runmean7']] # 
# X12=data[['DHW_9','CF_a_runmean7']] # +
# X15=data[['DHW_9','CF_a_runmean90']] # 
# X16=data[['DHW_9','CFrunmean7','CD']] # x
# X17=data[['DHW_9','CFrunmean7','WD']] # x
# X18=data[['SSTrunmax90','CF_a_runmean90','WD']] # +++
# X19=data[['DHW','CF_a_runmean7','CV_run7']] # +
# X20=data[['DHW','CF_a_runmean30','CV_run30']] # +
# X21=data[['DHW','CF_a_runmean90','CV_run90']] # -
# X22=data[['SSTrunmean90','CF_a_runmean90','WD']] # +
# X23=data[['SSTrunmean7','CF_a_runmean90','WD']]
# X24=data[['SSTrunmax7','CF_a_runmean90','WD']] # ++
# X25=data[['YEAR','DHW_9','CF_a_runmean7']] # +
# X26=data[['YEAR','DHW','CF_a_runmean90']] # +
# X27=data[['YEAR','CF_a_runmean90']] # -   VIF + 1,5
# X28=data[['YEAR','SSTrunmax7','CFrunmean90']] # 
# X30=data[['YEAR','SSTrunmax90','DHW','CV_run90']] # +++
# X31=data[['YEAR','SSTrunmax90','DHW','CV_run90','CFrunmean90']] # +++
# X32=data[['DHW_adj_date', 'CFrunmean90_adj_date']] # YEAR + DHW_9 VIF + 1.5
# #labels (indipendent variable)
# y=data['SEVERITY_CODE'] 

In [38]:
'''
Iterable object to run the models 
Here you can set the model's desired variables
'''
X=data[['DHM', 'CLT2017', 'RSDS']]## Features (dependent variable(s)); select desired variables
#X = data.loc[:,('DHW','CLT2017')]  ### ALTERNATIVE
y=data['SEVERITY_CODE'] # labels (indipendent variable)

In [39]:
'''
    Variance inflation factor VIF
'''
from statsmodels.stats.outliers_influence import variance_inflation_factor
# Get variables for which to compute VIF and add intercept term
X['Intercept'] = 1
# Compute and view VIF
vif = pd.DataFrame()
vif["variables"] = X.columns
vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
# View results using print
print(vif)

   variables       VIF
0        DHM  1.000302
1    CLT2017  2.276749
2       RSDS  2.276309
3  Intercept  1.592860


C:\Users\bmped\Miniconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


# Random forest classifier

In [36]:
'''
    Build the models
'''
model = RandomForestClassifier(n_estimators=200, random_state=3)
model.fit(X,y)
# evaluate the model
cv = RepeatedKFold(n_splits=5, n_repeats=10, random_state=3)
n_scores = cross_val_score(model, X, y, cv=cv) #n_jobs=-1, error_score='raise'

In [32]:
'''
    Report performance
'''
print('Cross val score: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))
print('\n')
# Features importance
print('=== features importances ===')
fi = pd.DataFrame({'feature': list(X.columns),
                   'importance': model.feature_importances_}).\
                    sort_values('importance', ascending = False)
fi

Cross val score: 0.655 (0.005)


=== features importances ===


feature  importance
1       RSDS    0.658001
0        DHM    0.341999
2  Intercept    0.000000

In [37]:
'''
    Confusion matrix
'''
y_pred=model.predict(X)
conf_mat = confusion_matrix(y, y_pred)
conf_mat_norm = confusion_matrix(y, y_pred,normalize='all')
print("=== Confusion matrix ===")
print(conf_mat)
print('\n')
print("=== Confusion matrix normalized ===")
print(conf_mat_norm)
print('\n')
print("=== Classification Report ===")
print(classification_report(y, y_pred))
print('\n')
print('=== Accuracy and Kappa ===')
print('accuracy', metrics.accuracy_score(y, y_pred))
print('\n')
print('kappa', metrics.cohen_kappa_score(y, y_pred))
print('\n')

=== Confusion matrix ===
[[12998   840   350    52]
 [ 1610  4787   852    89]
 [  666   649  5599   543]
 [  144   100   892  3431]]


=== Confusion matrix normalized ===
[[0.38682221 0.02499851 0.01041605 0.00154753]
 [0.04791381 0.14246176 0.02535563 0.00264865]
 [0.01982025 0.01931433 0.16662699 0.01615975]
 [0.00428546 0.00297601 0.02654604 0.10210702]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.84      0.91      0.88     14240
           1       0.75      0.65      0.70      7338
           2       0.73      0.75      0.74      7457
           3       0.83      0.75      0.79      4567

    accuracy                           0.80     33602
   macro avg       0.79      0.77      0.78     33602
weighted avg       0.80      0.80      0.80     33602



=== Accuracy and Kappa ===
accuracy 0.7980179751205285


kappa 0.7100709413276404




In [34]:
'''
    Evaluation between classifications models through "log loss"
'''
model_probs = model.predict_proba(X)
score = log_loss(y, model_probs)

'''
    Evaluation between classifications models through "ROC_AUC"
'''
roc_value = roc_auc_score(y, model_probs, multi_class='ovo') # ovo': Computes the average AUC of all possible pairwise combinations of classes


print('=== roc_auc_score ===') 
print(roc_value)
print(' ')
print('=== log_loss_score ===') 
print(score)


=== roc_auc_score ===
0.954297793198757
 
=== log_loss_score ===
0.45824231578571356


In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt     
ax = plt.subplot()
#Heat map with annot=True to annotate cells
sns.heatmap(conf_mat, annot=True, ax = ax, fmt='d', cmap='Blues') # actual cases
#sns.heatmap(conf_mat/np.sum(conf_mat), annot=True, ax = ax, fmt='.2%', cmap='Blues') #percentage
# labels, title and ticks
ax.set_xlabel('Predicted bleaching level');ax.set_ylabel('True bleaching level'); 
ax.set_title('Confusion Matrix'); 
ax.xaxis.set_ticklabels(['level 0','level 1','level 2', 'level 3']); ax.yaxis.set_ticklabels(['level 0','level 1','level 2', 'level 3'])
#plt.show()
#plt.savefig('DHW9_CF_a_runmean90.pdf', dpi=300)

In [ ]:
comparisons = pd.DataFrame({'Real':y, 'Predictions':y_pred})
comparisons.to_csv('pred_DHW_CF_a_runeman90.csv')
print(comparisons[['Real','Predictions']])

In [ ]:
data.to_csv('df_for_RFoutputs.csv')